sudo: required

services:
  - docker

language: ruby

env:
    global:
        - DOCKER_ENGINE_VERSION=1.11.2
        - DOCKER_COMPOSE_VERSION=1.7.1
        - DOCKER_MACHINE_VERSION=0.7.0
        - DOCKER_DIR=${TRAVIS_BUILD_DIR}/docker

before_install:
    # list docker-engine versions
    - apt-cache madison docker-engine

    # travis documentation says I'm in trusty container
    - lsb_release -a | grep trusty

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker version | grep ${DOCKER_ENGINE_VERSION}

    # reinstall docker-compose at specific version
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker-compose version | grep ${DOCKER_COMPOSE_VERSION}

    # install docker-machine at specific version
    - curl -L https://github.com/docker/machine/releases/download/v{DOCKER_COMPOSE_VERSION}/docker-machine-`uname -s`-`uname -m` > docker-machine
    - chmod +x docker-machine
    - sudo mv docker-machine /usr/local/bin
    #- docker-machine version  FAILS ???

    # smoke test
    - docker run --rm hello-world
    - docker images

script:
    # Build the cyber-dojo web image
    #- cd ${DOCKER_DIR}/nginx
    #- ./build-image.sh
    #- cd ${DOCKER_DIR}/user-base
    #- ./build-image.sh
    #- cd ${DOCKER_DIR}/web-base
    #- ./build-image.sh
    - cd ${DOCKER_DIR}/web
    - ./build-image.sh ${DOCKER_ENGINE_VERSION}
    - cd ${TRAVIS_BUILD_DIR}/cli
    - ./cyber-dojo up
    - cid=`docker ps --all --quiet --filter "name=cyber-dojo-web"`
    - docker logs cyber-dojo-web
    - docker inspect -f {{.State.Running}} ${cid}
    - docker ps -a
    #- docker --debug exec ${cid} sh -c "cd test && ./run.sh"
    - docker         exec ${cid} sh -c "cd test && ./run.sh"
