
sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

script:
    - ./build-image.sh ${DOCKER_ENGINE_VERSION}
    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo
    - sudo ./cyber-dojo up

    - cid=`docker ps --all --quiet --filter "name=cyber-dojo-web"`
    - docker logs cyber-dojo-web
    - docker inspect -f {{.State.Running}} ${cid}
    - docker ps -a

    # pull images used in tests so test-duration does not include pull time
    - docker pull cyberdojofoundation/gcc_assert:latest
    - docker pull cyberdojofoundation/ruby_test_unit:latest

    #- docker --debug exec ${cid} sh -c "cd test && ./run.sh"
    - docker         exec ${cid} sh -c "cd test && ./run.sh"

after_success:
    - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - docker push cyberdojo/web:${DOCKER_ENGINE_VERSION}

