
sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

script:
    - ./build.sh

    - curl -O https://raw.githubusercontent.com/cyber-dojo/commander/master/cyber-dojo
    - chmod +x cyber-dojo
    - ./cyber-dojo up

    # pull images used in tests so test-duration does not include pull time
    - docker pull cyberdojofoundation/gcc_assert:latest
    - docker pull cyberdojofoundation/ruby_test_unit:latest

    - ./test.sh

after_success:
    - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - if [ "${BRANCH}" == "master" ]; then
        docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}";
        docker push cyberdojo/web;
      fi

