sudo: required

services:
  - docker

language: ruby

script:
  - docker images

env:
    global:
        - DOCKER_VERSION=1.11.2-0~trusty
        - DOCKER_COMPOSE_VERSION=1.7.0
        - DOCKER_MACHINE_VERSION=0.6.0

before_install:
    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

    # reinstall docker-compose at specific version
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    # install docker-machine at specific version
    - curl -L https://github.com/docker/machine/releases/download/v{DOCKER_COMPOSE_VERSION}/docker-machine-`uname -s`-`uname -m` > docker-machine
    - chmod +x docker-machine
    - sudo mv docker-machine /usr/local/bin


script:
    - docker version
    - docker-compose version
    - docker images
    # Build the cyber-dojo images
    - cd ${TRAVIS_BUILD_DIR}/app/docker/nginx
    - ./build-image.sh
    - cd ${TRAVIS_BUILD_DIR}/app/docker/user-base
    - ./build-image.sh
    - cd ${TRAVIS_BUILD_DIR}/app/docker/web
    - ./build-image.sh
    - cd ${TRAVIS_BUILD_DIR}/app/docker
    - ./cyber-dojo up
    - cid=`docker ps --all --quiet --filter "name=cdf-web"`
    - docker exec ${cid} sh -c "cd test && ./run.sh"
