
sudo: required

services:
  - docker

language: ruby

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2
        - DOCKER_COMPOSE_VERSION=1.8.1

after_success:
    - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - docker push cyberdojo/web:${DOCKER_ENGINE_VERSION}

before_install:
    # list docker-engine versions
    - apt-cache madison docker-engine
    # travis documentation says I'm in trusty container
    - lsb_release -a | grep trusty
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker version | grep ${DOCKER_ENGINE_VERSION}
    # reinstall docker-compose at specific version
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker-compose version | grep ${DOCKER_COMPOSE_VERSION}
    # smoke test
    - docker run --rm hello-world
    - docker images

script:
    - ./build-image.sh ${DOCKER_ENGINE_VERSION}
    - cd ${TRAVIS_BUILD_DIR}/cli
    - sudo ./cyber-dojo up
    - cid=`docker ps --all --quiet --filter "name=cyber-dojo-web"`
    - docker logs cyber-dojo-web
    - docker inspect -f {{.State.Running}} ${cid}
    - docker ps -a

    # pull images used in tests so test-duration does not include pull time
    - docker pull cyberdojofoundation/gcc_assert:latest
    - docker pull cyberdojofoundation/ruby_test_unit:latest

    #- docker --debug exec ${cid} sh -c "cd test && ./run.sh"
    - docker         exec ${cid} sh -c "cd test && ./run.sh"
