# the image names comprising the server are
#   cyberdojofoundation/nginx:latest
#   cyberdojofoundation/web:${DOCKER_VERSION}
# if these change then the upgrade command in
# cyber-dojo.rb will also need changing.

nginx:
  image: cyberdojofoundation/nginx
  container_name: cdf-nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  user: cyber-dojo
  image: ${CYBER_DOJO_WEB_SERVER}
  container_name: ${CYBER_DOJO_WEB_CONTAINER}
  command: rails server --environment=development    # WORKS
  #command: rails server --environment=production    # FAILS. web:1.11.2 exits immediately
  #command: rails server --environment=test          # FAILS. web:1.11.2 exits immediately
  environment:
    - CYBER_DOJO_SHELL_CLASS
    - CYBER_DOJO_DISK_CLASS
    - CYBER_DOJO_LOG_CLASS
    - CYBER_DOJO_GIT_CLASS
    - CYBER_DOJO_KATAS_CLASS
    - CYBER_DOJO_RUNNER_CLASS
    - CYBER_DOJO_RUNNER_SUDO
    - CYBER_DOJO_RUNNER_TIMEOUT
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_DATA_HOME}/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_DATA_HOME}/exercises
    - CYBER_DOJO_INSTRUCTIONS_ROOT=${CYBER_DOJO_DATA_HOME}/instructions
    - CYBER_DOJO_KATAS_ROOT=${CYBER_DOJO_DATA_HOME}/katas
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${CYBER_DOJO_LANGUAGES_VOLUME}:${CYBER_DOJO_DATA_HOME}/languages:ro
    - ${CYBER_DOJO_EXERCISES_VOLUME}:${CYBER_DOJO_DATA_HOME}/exercises:ro
    - ${CYBER_DOJO_INSTRUCTIONS_VOLUME}:${CYBER_DOJO_DATA_HOME}/instructions:ro
  volumes_from:
    - ${CYBER_DOJO_KATAS_DATA_CONTAINER}:rw

